//Pokemon

export const START_GET_POKEMON = "START_GET_POKEMON";
export const GET_POKEMON_SUCCESS = "GET_POKEMON_SUCCESS";
export const GET_POKEMON_FAILED = "GET_POKEMON_FAILED";

//pokemon detail
export const START_GET_POKEMON_DETAIL = "START_GET_POKEMON_DETAIL";
export const GET_POKEMON_DETAIL_SUCCESS = "GET_POKEMON_DETAIL_SUCCESS";
export const GET_POKEMON_DETAIL_FAILED = "GET_POKEMON_DETAIL_FAILED";